/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd.leesper.jargs;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    // -l -p 8080 -d /usr/logs
    // Single option
    @Test
    public void shouldSetBooleanOptionToTrueIfFlagPresent() {
        BooleanOption option = Args.parse(BooleanOption.class, "-l");
        assertTrue(option.logging());
    }

    @Test
    public void shouldSetBooleanOptionToFalseIfFlagNotPresent() {
        BooleanOption option = Args.parse(BooleanOption.class);
        assertFalse(option.logging());
    }

    static record BooleanOption(@Option("l") boolean logging) {}

    @Test
    public void shouldParseIntAsOptionValue() {
        IntOption option = Args.parse(IntOption.class, "-p", "8080");
        assertEquals(8080, option.port());
    }

    static record IntOption(@Option("p") int port) {}

    @Test
    public void shouldGetStringAsOptionValue() {
        StringOption option = Args.parse(StringOption.class, "-d", "/usr/logs");
        assertEquals("/usr/logs", option.directory());
    }

    static record StringOption(@Option("d") String directory) {}

    @Test
    public void shouldParseMultiOptions() {
        MultiOptions options = Args.parse(MultiOptions.class, "-l", "-p", "8080", "-d", "/usr/logs");
        assertTrue(options.logging());
        assertEquals(8080, options.port());
        assertEquals("/usr/logs", options.directory());
    }

    static record MultiOptions(@Option("l") boolean logging, @Option("p") int port, @Option("d") String directory) {}
    // Sad path
    //   TODO: - bool -l t / -l t f
    //   TODO: - integer -p / -p 8080 8081
    //   TODO: - string -d / -d /usr/logs /usr/vars
    // Default
    //   TODO: - bool : false
    //   TODO: - integer : 0
    //   TODO: - string : ""


    // -g this is a list -d 1 2 -3 5
    @Test
    @Disabled
    public void should_example_2() {
        ListOptions options = Args.parse(ListOptions.class, "-g", "this", "is", "a", "list", "-d", "1", "2", "-3", "5");
        assertArrayEquals(new String[]{"this", "is", "a", "list"}, options.group());
        assertArrayEquals(new int[]{1, 2, -3, 5}, options.decimals());
    }



    static record ListOptions(@Option("g") String[] group, @Option("d") int[] decimals) {}
}
